#!/usr/bin/with-contenv bash

echo "Starting airupnp finish"

echo "/bin/airupnp-${ARCH_VAR}"
if [ ! -f /bin/airupnp-${ARCH_VAR} ]; then
    echo "/bin/airupnp-${ARCH_VAR} executable not found - /bin/aircast-"${ARCH_VAR}""
    exit 125
fi

echo "Exiting airupnp finish"
