#!/usr/bin/with-contenv bash

echo "Starting airupnp run"

if [ ! -f /bin/airupnp-"${ARCH_VAR}" ]; then
    echo "/bin/airupnp-"${ARCH_VAR}" executable not found - setting service to down"
    s6-svc -d airupnp
else
    echo "file exists"
    if [ -z "${AIRUPNP_VAR}" ]; then
       /bin/airupnp-"${ARCH_VAR}" -l 1000:2000
    else
       /bin/airupnp-"${ARCH_VAR}" "${AIRUPNP_VAR}"
    fi
fi

echo "Exiting airupnp run"
