#!/usr/bin/with-contenv bash

echo "Starting aircast finish"

if [ ! -f /bin/aircast-"${ARCH_VAR}" ]; then
    echo "/bin/aircast-"${ARCH_VAR}" executable not found - setting service to down"
    exit 125
fi

echo "Exiting aircast finish"
