#!/usr/bin/with-contenv bash

echo "Starting aircast run"

if [ ! -f /bin/aircast-"${ARCH_VAR}" ]; then
    echo "/bin/airupnp-"${ARCH_VAR}" executable not found - setting service to down"
    s6-svc -d aircast
else
    echo "file exists"
    if [ -z "${AIRCAST_VAR}" ]; then
       /bin/aircast-"${ARCH_VAR}"
    else
       /bin/aircast-"${ARCH_VAR}" "${AIRCAST_VAR}"
    fi
fi

echo "Exiting aircast run"
