#!/usr/bin/with-contenv bash

echo "=== Starting aircast run ==="

if [ "${AIRCAST_VAR}" == "kill" ]; then
    echo "=== Exiting aircast run - due to AIRCAST variable set to \"kill\" ==="
    exit 0
fi

if [ "$ARCH_VAR" == "amd64" ]; then
  ARCH_VAR=linux-x86_64
elif [ "$ARCH_VAR" == "arm64" ]; then
  ARCH_VAR=linux-aarch64
elif [ "$ARCH_VAR" == "arm" ]; then
  ARCH_VAR=linux-arm
fi

echo " ARCH_VAR=${ARCH_VAR}"
ARCH_VAR="${ARCH_VAR}-static"

if [ -f /bin/aircast-${ARCH_VAR} ]; then
    echo " executable /bin/aircast-"${ARCH_VAR}" exists"
    if [ -z "${AIRCAST_VAR}" ]; then
       /bin/aircast-${ARCH_VAR}
    else
       /bin/aircast-${ARCH_VAR} ${AIRCAST_VAR}
    fi
fi

echo "=== Exiting aircast run ==="
