#!/usr/bin/with-contenv bash

echo "Starting aircast run"

if [ "$ARCH_VAR" == "amd64" ]; then
  ARCH_VAR=linux-x86_64
elif [ "$ARCH_VAR" == "arm64" ]; then
  ARCH_VAR=linux-aarch64
# elif [ "$ARCH_VAR" == "arm" ]; then
#   ARCH_VAR=linux-arm
fi

echo "Checking for valid arch options"
case $ARCH_VAR in
  linux-x86_64)
    echo "Proceeding with linux-x86_64 arch"
    ;;
  linux-aarch64)
    echo "Proceeding with linux-aarch64 arch"
    ;;
  # linux-arm)
  #   echo "Proceeding with linux-arm arch"
  #   ;;
  *)
    echo "Unrecognized or invalid arch selection, CANCELING INSTALL"
    echo "========== FAILURE DETECTED ========="
    echo "YOUR CONTAINER WILL NOT WORK, PLEASE ADDRESS OR OPEN AN ISSUE"
    exit 1
    ;;
esac

echo "ARCH_VAR=${ARCH_VAR}"
ARCH_VAR="${ARCH_VAR}-static"


if [ ! -f /bin/aircast-"${ARCH_VAR}" ]; then
    echo "/bin/aircast-"${ARCH_VAR}" executable not found - setting service to down"
    s6-svc -d /var/run/s6/services/aircast
else
    echo "file exists"
    if [ -z "${AIRCAST_VAR}" ]; then
       echo "/bin/aircast-${ARCH_VAR} -h"
       /bin/aircast-${ARCH_VAR} -h
       /bin/aircast-${ARCH_VAR} -Z
    else
       /bin/aircast-"${ARCH_VAR}" "${AIRCAST_VAR}"
    fi
fi

echo "Exiting aircast run"
